# Generated by Django 3.2.5 on 2022-01-25 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_skillset'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='profiles.skillset'),
            preserve_default=False,
        ),
    ]
