# Generated by Django 3.2.5 on 2022-01-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_profile_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.FileField(default=1, upload_to='cv/'),
            preserve_default=False,
        ),
    ]
